package _010_Automating_GUI_WebElements_of_WebPage._8_Handling_AJAX_AutoSuggestions_in_a_Webpage;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class _print_the_AutoSuggested_options_in_Console
{

	public static void main(String[] args) 
	{
		System.setProperty("webdriver.chrome.driver", "chromedriver.exe");

		WebDriver driver = new ChromeDriver();
		
		driver.manage().deleteAllCookies();
		driver.manage().window().maximize();
		
		driver.get("https://www.google.com/imghp?hl=en&tab=ri&authuser=0&ogbl");
		
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		Actions action = new Actions(driver);
		
		WebElement input_SearchBox = driver.findElement(By.xpath("//textarea[@name = 'q']"));	
		

		action.moveToElement(input_SearchBox).sendKeys("ELDEN RING").perform();

		/* First Find te autogenerated Unordered List, then capture all List items in it */
		List<WebElement> autogenerated_keywordlist = driver.findElement(By.xpath("(//ul[@role='listbox'])[1]")).findElements(By.tagName("li"));
		
		System.out.println("Auto-Suggestions: ");
		for(WebElement element : autogenerated_keywordlist)
		{
			String keyword = element.getText();
			
			System.out.println(keyword);
		}

		/* Click element of choice */
		for(WebElement desired_element : autogenerated_keywordlist)
		{
			String desired_keyword = desired_element.getText();
			if(desired_keyword.equalsIgnoreCase("elden ring shadow of the erdtree"))
			{	
				System.out.println("Click on '" + desired_element.getText() + "' ");
				desired_element.click();		
				
				break;
			}
			
		}
		
	}

}
